databases.diagnostic.datasources.jdbc.customvdpcachedatasource.DATABASEURI=jdbc\:derby\://localhost\:1527/cache
databases.diagnostic.datasources.jdbc.customvdpcachedatasource.USERNAME=vdpcache
databases.diagnostic.datasources.jdbc.customvdpcachedatasource.USERPASSWORD=muTkdspVWqU40+G67/AtkPEZGvXUEqOwzOnrYwn0ULEYKTWQA0uF5+bJNoMlIBlckwd5/X6Or2QuddUlR3nb9MVx0SJeI0h8priBiXouR9kdrCwJgehi1FSfTGugScK+bBRbHIcxumrxejtLv1Xvvg\=\=
databases.diagnostic.datasources.jdbc.customvdpcachedatasource.USERPASSWORD.ENCRYPTED=ENCRYPTED
