databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.DATABASEURI=jdbc\:postgresql\://localhost\:5432/DENODO9
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERNAME=postgres
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERPASSWORD=K7+JpY7lsLIySr3n8zK/i133s95ExllrMOwggtH2ZO6egn2NOmZVWQx9L/LLGnhcZFBv9hUEz8+CYsAwIrSkiuECNR/o2XlZuDYk5dmdcSldzfiXdtvD+TRwShi6YBzc
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERPASSWORD.ENCRYPTED=ENCRYPTED
