databases.admin.folder.connectivity.folder.data\ sources.datasources.ldap.dummy_ldap.URI=ldap\://localhost\:389
databases.admin.folder.connectivity.folder.data\ sources.datasources.ldap.dummy_ldap.USERNAME=cn\=admin,dc\=example,dc\=com
databases.admin.folder.connectivity.folder.data\ sources.datasources.ldap.dummy_ldap.USERPASSWORD=1Syf9xwEcPlv7SX/m8eyCsqSWj2D4E6VFDG2YGfwbSF3EhYRQRVa9Zr4bSKPWOdRLh1z1vG7u5IZ0MIjT82X5oC15zO2z9v2auiY141m1/kqDijSEmABqKWHyIAjbNVe
databases.admin.folder.connectivity.folder.data\ sources.datasources.ldap.dummy_ldap.USERPASSWORD.ENCRYPTED=ENCRYPTED
