databases.sql_db.folder.connectivity.folder.data\ sources.datasources.jdbc.my_testie.DATABASEURI=jdbc\:mysql\://localhost\:3306/testie
databases.sql_db.folder.connectivity.folder.data\ sources.datasources.jdbc.my_testie.USERNAME=root
databases.sql_db.folder.connectivity.folder.data\ sources.datasources.jdbc.my_testie.USERPASSWORD=70W1kFuDIkmGU2b/TWgU/YV29q9IXHqvBedO7fmcrY1p95mOTWOCq1stKpbhSsE7HSxyvxzbSDDeodI0R3GCc+/fo+rIzFOaiexE8Ig4amNlkLMVcGtkG1/aAuePMLj7
databases.sql_db.folder.connectivity.folder.data\ sources.datasources.jdbc.my_testie.USERPASSWORD.ENCRYPTED=ENCRYPTED
