databases.admin.datasources.json.ur_mom.ROUTE.HTTP.PASSWORD=jLYSTQ4thde4R4E8YsZwh9KZ9O4fLFh2JYwgESHz4Ok66jm8XM9MMDyChm7t9sMUuf0+XGfGMSXI1h6FJJFrJY7hyvJqLwpceUyOkx7WAtFVqz0u0xX/wTQBj4ZUWwCE
databases.admin.datasources.json.ur_mom.ROUTE.HTTP.PASSWORD.ENCRYPTED=ENCRYPTED
databases.admin.datasources.json.ur_mom.ROUTE.HTTP.URL=https\://localhost\:9443/denodo-data-catalog/public/api
databases.admin.datasources.json.ur_mom.ROUTE.HTTP.USER=admin
